#!/usr/bin/env python3
"""GENERATOR for src/unicode_props.zig - Unicode property -> code-point range tables for regex
`\\p{...}` escapes. Derived from Python `unicodedata` (Unicode 13.0, matching unicode_id.zig).
General_Category groups + subcategories, plus a curated set of binary properties.
Run: python specs/140-unicode-property-regex/gen_props.py > src/unicode_props.zig
"""
import unicodedata, sys
sys.stdout.reconfigure(encoding='utf-8')

MAX = 0x110000

# General_Category subcategories (the 2-letter ones unicodedata reports), grouped by first letter.
SUBCATS = ["Lu","Ll","Lt","Lm","Lo","Mn","Mc","Me","Nd","Nl","No",
           "Pc","Pd","Ps","Pe","Pi","Pf","Po","Sm","Sc","Sk","So",
           "Zs","Zl","Zp","Cc","Cf","Cs","Co"]
GROUPS = {"L":["Lu","Ll","Lt","Lm","Lo"], "M":["Mn","Mc","Me"], "N":["Nd","Nl","No"],
          "P":["Pc","Pd","Ps","Pe","Pi","Pf","Po"], "S":["Sm","Sc","Sk","So"],
          "Z":["Zs","Zl","Zp"], "C":["Cc","Cf","Cs","Co","Cn"]}

# Build a category array for every code point (Cn = unassigned).
cat = [None]*MAX
for cp in range(MAX):
    cat[cp] = unicodedata.category(chr(cp))

def ranges_for(pred):
    out, start = [], None
    for cp in range(MAX):
        if pred(cp):
            if start is None: start = cp
        else:
            if start is not None: out.append((start, cp-1)); start = None
    if start is not None: out.append((start, MAX-1))
    return out

# White_Space property (Unicode PropList) - fixed small set.
WS = {0x09,0x0A,0x0B,0x0C,0x0D,0x20,0x85,0xA0,0x1680,0x2028,0x2029,0x202F,0x205F,0x3000}
WS |= set(range(0x2000,0x200B))
# Default_Ignorable_Code_Point (derived) - the principal ranges (Unicode 13).
DI = set([0xAD,0x34F,0x061C,0x115F,0x1160,0x17B4,0x17B5,0x3164,0xFEFF,0xFFA0,0xE0001])
DI |= set(range(0x180B,0x180F)) | set(range(0x200B,0x2010)) | set(range(0x2060,0x2065))
DI |= set(range(0x2065,0x2070)) | set(range(0xFE00,0xFE10)) | set(range(0xFFF0,0xFFF9))
DI |= set(range(0x1BCA0,0x1BCA4)) | set(range(0x1D173,0x1D17B)) | set(range(0xE0000,0xE1000))

tables = {}
for sc in SUBCATS:
    tables[sc] = ranges_for(lambda cp, s=sc: cat[cp]==s)
for g, subs in GROUPS.items():
    if g == "C":  # Other includes Cn (unassigned) per UCD
        tables[g] = ranges_for(lambda cp: cat[cp][0]=="C" or cat[cp]=="Cn")
    else:
        tables[g] = ranges_for(lambda cp, ss=set(subs): cat[cp] in ss)
tables["White_Space"] = ranges_for(lambda cp: cp in WS)
tables["Alphabetic"]  = ranges_for(lambda cp: cat[cp] in ("Lu","Ll","Lt","Lm","Lo","Nl"))
tables["Default_Ignorable_Code_Point"] = ranges_for(lambda cp: cp in DI)
tables["Assigned"]    = ranges_for(lambda cp: cat[cp] != "Cn")

def emit(name, rs):
    print(f"const t_{name} = [_]R{{")
    line = "    "
    for (a,b) in rs:
        seg = f".{{ 0x{a:X}, 0x{b:X} }}, "
        if len(line)+len(seg) > 116: print(line.rstrip()); line = "    "
        line += seg
    if line.strip(): print(line.rstrip())
    print("};")

print("//! GENERATED by specs/140-unicode-property-regex/gen_props.py - DO NOT hand-edit.")
print("//! Unicode property -> code-point ranges for regex `\\p{...}` (Unicode 13.0 via unicodedata).")
print("//! General_Category groups + subcategories + curated binaries. `Any`/`ASCII` are computed.")
print("const std = @import(\"std\");")
print("const R = [2]u21;")
print()
order = ["L"]+["Lu","Ll","Lt","Lm","Lo"]+["M","Mn","Mc","Me"]+["N","Nd","Nl","No"]
order += ["P","Pc","Pd","Ps","Pe","Pi","Pf","Po"]+["S","Sm","Sc","Sk","So"]
order += ["Z","Zs","Zl","Zp"]+["C","Cc","Cf","Cs","Co"]
order += ["White_Space","Alphabetic","Default_Ignorable_Code_Point","Assigned"]
for name in order:
    emit(name, tables[name])
    print()

# PropId enum + name lookup + table dispatch.
print("pub const PropId = enum { " + ", ".join(order) + ", Any, ASCII };")
print()
print("/// Resolve a `\\p{...}` property NAME (short General_Category value, or a curated binary /")
print("/// alias) to a PropId. Returns null for an unknown property (-> caller SyntaxError).")
print("pub fn lookup(name: []const u8) ?PropId {")
print("    const eq = std.mem.eql;")
aliases = {
    "L":["L","Letter"],"Lu":["Lu","Uppercase_Letter"],"Ll":["Ll","Lowercase_Letter"],
    "Lt":["Lt","Titlecase_Letter"],"Lm":["Lm","Modifier_Letter"],"Lo":["Lo","Other_Letter"],
    "M":["M","Mark","Combining_Mark"],"Mn":["Mn","Nonspacing_Mark"],"Mc":["Mc","Spacing_Mark"],"Me":["Me","Enclosing_Mark"],
    "N":["N","Number"],"Nd":["Nd","Decimal_Number","digit"],"Nl":["Nl","Letter_Number"],"No":["No","Other_Number"],
    "P":["P","Punctuation","punct"],"Pc":["Pc","Connector_Punctuation"],"Pd":["Pd","Dash_Punctuation"],
    "Ps":["Ps","Open_Punctuation"],"Pe":["Pe","Close_Punctuation"],"Pi":["Pi","Initial_Punctuation"],
    "Pf":["Pf","Final_Punctuation"],"Po":["Po","Other_Punctuation"],
    "S":["S","Symbol"],"Sm":["Sm","Math_Symbol"],"Sc":["Sc","Currency_Symbol"],"Sk":["Sk","Modifier_Symbol"],"So":["So","Other_Symbol"],
    "Z":["Z","Separator"],"Zs":["Zs","Space_Separator"],"Zl":["Zl","Line_Separator"],"Zp":["Zp","Paragraph_Separator"],
    "C":["C","Other"],"Cc":["Cc","Control","cntrl"],"Cf":["Cf","Format"],"Cs":["Cs","Surrogate"],"Co":["Co","Private_Use"],
    "White_Space":["White_Space","space","Whitespace","White_space"],
    "Alphabetic":["Alphabetic","Alpha"],
    "Default_Ignorable_Code_Point":["Default_Ignorable_Code_Point","DI"],
    "Assigned":["Assigned"],
}
for pid in order:
    conds = " or ".join(f'eq(u8, name, "{a}")' for a in aliases[pid])
    print(f"    if ({conds}) return .{pid};")
print('    if (eq(u8, name, "Any")) return .Any;')
print('    if (eq(u8, name, "ASCII")) return .ASCII;')
print("    return null;")
print("}")
print()
print("fn tableOf(id: PropId) []const R {")
print("    return switch (id) {")
for name in order:
    print(f"        .{name} => &t_{name},")
print("        .Any, .ASCII => &.{},")
print("    };")
print("}")
print()
print("/// True iff `cp` has property `id`. `Any` = all; `ASCII` = cp < 0x80; else binary-search ranges.")
print("pub fn contains(id: PropId, cp: u21) bool {")
print("    switch (id) {")
print("        .Any => return true,")
print("        .ASCII => return cp < 0x80,")
print("        else => {},")
print("    }")
print("    const ranges = tableOf(id);")
print("    var lo: usize = 0; var hi: usize = ranges.len;")
print("    while (lo < hi) {")
print("        const mid = lo + (hi - lo) / 2;")
print("        if (cp < ranges[mid][0]) hi = mid")
print("        else if (cp > ranges[mid][1]) lo = mid + 1")
print("        else return true;")
print("    }")
print("    return false;")
print("}")
